export const RECEIPT_HEADER_LINES = [
  'PROVINCIA DE BUENOS AIRES',
  'DIRECCION GENERAL DE CULTURA Y EDUCACION',
  'DIRECCION GENERAL DE ADMINISTRACION',
  'DGCyE CUIT N° 30-62739371-3',
] as const

